### ISSUE TITLE
Duygu Durum Oranları

### ISSUE THREAD

**Issue by irem6142** [irem6142/data-segmentation-and-sentiment-analysis#1]
@rumeysacelik   @MuratOgurlu  @ENESAKICI  sadece pozitif ne negatiflik var nötr duygu oranı eklenmesi lazım.

**Comment by MuratOgurlu** [comment]
İndirme butonu eklenmesi iyi olabilir @irem6142 @rumeysacelik @ENESAKICI

**Comment by rumeysacelik** [comment]
Pozitif ve negatif oranlarının verilmesi yeterli olur diye düşünüyorum ama yine de ekipçe bir değerlendirelim. 
Kesinlikle! İndirme butonu eklememiz harika olacaktır.

**Comment by irem6142** [comment]
@EmirhanVarlk  indirme butonunu eklesen güzel olur.

**Comment by EmirhanVarlk** [comment]
@irem6142 zaten sonuçlar extensionda % ile beraber görünüyor indirme butonuna gerek yok.

**Comment by ENESAKICI** [comment]
@EmirhanVarlk  ve @rumeysacelik  katılıyorum

**Comment by ENESAKICI** [comment]
@EmirhanVarlk ve @rumeysacelik e katılıyorum, nötr duyguya gerek yok.
